### ISSUE TITLE
Adicionar padrão de codificação a ser auditado pelo checkstyle (base)

### ISSUE THREAD

**Issue by duartefq** [JoabMendes/peteka#141]

**Comment by duartefq** [comment]
There are 1487 errors reported by Checkstyle 7.0 with src/checkconfig/checkstyle/checkstyle.xml ruleset. 
@JoabMendes @VictorLimeira 
![hmm](https://i.imgur.com/KWl6pqT.jpg)

**Comment by JoabMendes** [comment]
gzuz
![ohmy](https://nobodyputsbabyinahorner.files.wordpress.com/2013/11/tumblr_inline_mibgvynyco1qz4rgp.gif)
