### ISSUE TITLE
Adicionar AngujarJS as dependencias

### ISSUE THREAD

**Issue by VictorLimeira** [JoabMendes/peteka#3]
Será que seria legal usarmos o angular nesse projeto pra testar @JoabMendes @duartefq ?! Só pra testar? Queria aprender.

**Comment by JoabMendes** [comment]
Como o professor falou, a gente vai usar aquelas bibliotecas pra visão. Então por enquando a gente tentar seguir igual com ele. Caso a gente precise inovar, a gente usa. :+1:
