### ISSUE TITLE
Implementar Testes das Funções dos Repositórios que usam QueryDSL

### ISSUE THREAD

**Issue by JoabMendes** [JoabMendes/peteka#89]
- [x] TaskRepositoryIT - getAllTasksForProject

- [x] UserRepositoryIT - getAllUsersOfRole

- [x] TaskRepositoryIT - getAllTasksForProjectOfStatus

- [x] ProjectRepositoryIT - getAllProjectsOfUser

**Comment by duartefq** [comment]
Closed by b707251 and e7dafd8
