### ISSUE TITLE
Task 8: Fazer descrição do projeto da wiki

### ISSUE THREAD

**Issue by JoabMendes** [JoabMendes/peteka#9]
Apenas o tópico de descrição.
https://github.com/JoabMendes/peteka/wiki

**Comment by VictorLimeira** [comment]
Coloquei a descrição, acredito que está cobrindo a maioria do que o sistema deveria fazer, não discutimos muito o que seria o sistema, mas fiz essa descrição com o sistema do runrunit em mente.
